# Site settings
title: Bhushan Raut
twitter_username: bhushanraut1811
name: Bhushan Raut

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Quora
   url: https://quora.com/profile/Bhushan-Raut?srid=T1jz&share=d32fda73
 - title: GitHub
   url: https://github.com/bhushanraut1811
 - title: StackOverflow
   url: http://stackoverflow.com/users/5638613/nlogn
 - title: AngelList
   url: https://angel.co/bhushanraut1811
 - title: LinkedIn
   url: https://www.linkedin.com/in/bhushanraut1811

#Any buzzword skills you want to include
skills:
 - Java
 - Spring MVC
 - Appium
 - Gradle
 - Java
 - SQL
 - REST
 - Groovy
 - Linux

#Work experience is required
roles:
 - title: Associate Software Engineer
   start: Nov 2015
   end: Ongoing
   employer: GlobalLogic India
   description: Working on Health Care domain project in which facing challenge of development as well as automation.

#Education is required
education:
 - level: Bachelor of Engineering (Computer Science & Engineering)
   date: 2011-15
   score: 7.86 
   school: Shri Ramdeobaba College of Engineering and Management,Nagpur,Inida
   
#schooling
education:
 - level: HSC (Maharashtra State Board)
   date: 2010-11
   score: 90.30%
   school: Dharampeth Science College,Nagpur,Inida
   
education:
 - level: SSC (Maharashtra State Board)
   date: 2008-09
   score: 81.50%
   school: Dharampeth Science College,Nagpur,Inida   
   
   

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
 - bhushanraut1811/TagLayout-Android-Library
 - bhushanraut1811/CodingContestsApp
 - bhushanraut1811/WordsNotifier-Python
 - bhushanraut1811/SmsApp-with-Google-Drive-backup

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/5638613/nlogn?tab=profile
   flairimageurl: http://stackoverflow.com/users/flair/5638613.png

#Mobile apps section is optional
apps:
 - name: Coding Contest App
   logo: https://lh3.googleusercontent.com/ggLaFvlnHRFn9h1yS2G67zyfRxh7AdgeEk6r-Ki3CbityuH4y7Z5yA9_AY46N5Z8vSg=w300
   platform: Android
   url: https://play.google.com/store/apps/details?id=apps.techmines.codingcontestapp
   description: An App for active and upcoming coding contests
   
 - name: ShareWithMe
   logo: https://lh3.googleusercontent.com/uFiSBYPqVT4mgVfm0a3d_3eMVx9xmxyXdqgRIcO2vEJ-SZEmqiAgcg74bLZ6wAP-PDU=w300
   platform: Android
   url: https://play.google.com/store/apps/details?id=apps.techmines.sharewithme
   description: An App to locally share/manage the links

 - name: Flash Cards Quiz
   logo: https://lh3.googleusercontent.com/dcbPQwWt1c4E-y6vUsZrLHeVNE_ADeMKYUaeaYsG7GqrKwwvbXhGs-Jzhi3CF1d1DNaf=w300
   platform: Android
   url: https://play.google.com/store/apps/details?id=com.techmines.flashcards.quiz
   description: Test and learn English with Vocabulary flash cards
   
 - name: Banking Awareness Guide
   logo: https://lh3.googleusercontent.com/hpG0E9H_kZmrU0wsJ6Br6Scad_2oeWieOC0PtVavOtYi2cEypcEsA6HF2zMSxHcj0bA=w300
   platform: Android
   url: https://play.google.com/store/apps/details?id=com.techmines.bankawareness
   description: Complete offline guide for competitive exam preparation

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Android, Spring, JPA (Hibernate) in addition to others.  In my current role Java (Android Sdk) is the primary language used along with Groovy used for automation (Mobile Automation using Appium)- and I am familiar with python, C. <br/><br/>
   <strong>Mobile Development</strong>: I have worked on various Custom Views,fragments,Sqlite and other components in android development. I have also worked on Realm Database, Volley, Picaso, Retrofit and other frameworks for android development.Done some explorations in basic explorations in Google map api<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including mBaaS, Scala programming Language. <br/><br/>
   I have created api's in Java Spring for Coding Contest Andorid App and hosted it on AWS.
